-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 20:54:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema twitter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema twitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twitter` DEFAULT CHARACTER SET utf8 ;
USE `twitter` ;

-- -----------------------------------------------------
-- Table `twitter`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter`.`users` (
  `userID` INT NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `birthDate` DATE NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC))
ENGINE = InnoDB
COMMENT = 'idusers';


-- -----------------------------------------------------
-- Table `twitter`.`followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter`.`followers` (
  `userFollowID` INT NOT NULL,
  `followerID` INT NOT NULL,
  INDEX `fk_followers_users1_idx` (`userFollowID` ASC),
  INDEX `fk_followers_users2_idx` (`followerID` ASC),
  CONSTRAINT `fk_followers_users1`
    FOREIGN KEY (`userFollowID`)
    REFERENCES `twitter`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_followers_users2`
    FOREIGN KEY (`followerID`)
    REFERENCES `twitter`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter`.`twits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter`.`twits` (
  `twitID` INT NOT NULL,
  `twitText` VARCHAR(160) NOT NULL,
  `author` INT NOT NULL,
  `twitDate` DATETIME NOT NULL,
  PRIMARY KEY (`twitID`),
  UNIQUE INDEX `twitID_UNIQUE` (`twitID` ASC),
  INDEX `fk_twits_users_idx` (`author` ASC),
  CONSTRAINT `fk_twits_users`
    FOREIGN KEY (`author`)
    REFERENCES `twitter`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter`.`comments` (
  `commentID` INT NOT NULL,
  `commentDate` DATETIME NOT NULL,
  `commentText` VARCHAR(160) NOT NULL,
  `authorID` INT NOT NULL,
  `twitID` INT NOT NULL,
  PRIMARY KEY (`commentID`),
  UNIQUE INDEX `commentID_UNIQUE` (`commentID` ASC),
  INDEX `fk_comments_users1_idx` (`authorID` ASC),
  INDEX `fk_comments_twits2_idx` (`twitID` ASC),
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`authorID`)
    REFERENCES `twitter`.`users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_twits2`
    FOREIGN KEY (`twitID`)
    REFERENCES `twitter`.`twits` (`twitID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
